routes:
    home: 'Default:home'
    articles: 'Default:articles'
    profile: 'Security:profile'
    profileEditing: 'Security:profileEditing'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'

defaut_route: 'home'

db_config:
    name: 'vae_victis'
    host: 'localhost'
    user: 'vae_victis'
    pass: 'vae_victis'
